workflows:
  android-tv:
    name: Signing and deploying android TV application
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: true
    environment:
      flutter: 3.13.9
      vars:
        PACKAGE_NAME: "com.mawaqit.androidtv"
        GOOGLE_PLAY_TRACK: internal
      android_signing:
        - Mawaqit Mobile App + Android TV Android keystore
      groups:
        - google_credentials
        - aws_credentials
        - GITHUB
        - APP
    scripts:
      - name: Retrieve version
        script: |
          VERSION=$(cat "pubspec.yaml" | sed -nE 's/version:.*([0-9]+\.[0-9]+\.[0-9])(-tv)?\+.*/\1/p')
          BUILD_NUMBER=491
          VERSION=1.19.5
          echo "VERSION=$VERSION" >> $CM_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
      - name: Test version
        script: |
          echo "App version: $VERSION"
          echo "BUILD NUMBER: $BUILD_NUMBER"
          if [ -z ${VERSION} ]; then
           echo "Version is empty, will not proceed"
           exit 1
          fi
          if [ -z ${BUILD_NUMBER} ]; then
           echo "BUILD NUMBER is empty, will not proceed"
           exit 1
          fi
      - name: Download pre-built AAB and APK
        script: |
          mkdir -p build/artifacts
          APK_URL="https://files.catbox.moe/vhxkgj.apk"
          
          curl -o build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.aab "$AAB_URL"
          curl -o build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk "$APK_URL"
          
          if [ ! -f build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk ]; then
            echo "Failed to download APK file"
            exit 1
          fi
      - name: Sign Android files
        script: |
          # Create directory for signed files
          mkdir -p build/signed
          # Sign APK
          $ANDROID_HOME/build-tools/33.0.0/apksigner sign --ks $CM_KEYSTORE_PATH \
            --ks-pass pass:$CM_KEYSTORE_PASSWORD \
            --key-pass pass:$CM_KEY_PASSWORD \
            --ks-key-alias $CM_KEY_ALIAS \
            --v2-signing-enabled true \
            --v3-signing-enabled true \
            build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk
          
          # Verify APK signature
          $ANDROID_HOME/build-tools/33.0.0/apksigner verify -v build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk
          
          # Move signed files to signed directory
          cp build/artifacts/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk build/signed/MAWAQIT-For-TV-v$VERSION-$BUILD_NUMBER.apk

    artifacts:
      - build/artifacts/*
      - build/signed/*
      - build/**/outputs/**/mapping.txt