/// Flutter icons MawaqitIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MawaqitIcons
///      fonts:
///       - asset: fonts/MawaqitIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MawaqitIcons {
  MawaqitIcons._();

  static const _kFontFam = 'MawaqitIcons';
  static const _kFontPkg = null;

  //Logos
  static const IconData logo_dark = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_light = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_dark_inactive = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_dark_with_text = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_light_with_text = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_dark_with_text_horizontal =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_light_with_text_horizontal =
      IconData(0xe78, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //Calligraphy
  static const IconData arabic_calligraphy_salat_time = IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //Icons
  static const IconData icon_favorites = IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_favorites_inactive = IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_qibla = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_qibla_inactive = IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search_inactive = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_settings = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_settings_inactive = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification_bip = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification_silent = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification_adhan = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_adhan = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pre_notification = IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pre_notification_clock = IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pre_notification_bell = IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pre_notification_2 = IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pre_notification_3 = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_uk = IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_sa = IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_fr = IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_es = IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_tr = IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_pt = IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flag_nl = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_parking = IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_parking_disabled =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_ablutions = IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_ablutions_disabled =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_wheelchair = IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_wheelchair_disabled =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_woman = IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_woman_disabled =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_janazah = IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_janazah_diabled =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_children = IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_children_disabled =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_adults = IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_adults_disabled =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_aidsalat = IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_aidsalat_disabled =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_iftar = IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facilities_iftar_disabled =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_salat_aid = IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_left = IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_right = IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_updown = IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_view_card = IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_view_list = IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_play = IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pause = IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call = IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_disabled = IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mail = IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mail_disabled = IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_info = IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_megaphone = IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification = IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_delete = IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trash = IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_close = IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_back = IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_copy = IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_restart = IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque_selected = IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque_add = IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque_remove = IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_donation = IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_check = IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_check_disabled = IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_checked = IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification_bullet_red = IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification_bullet_grey = IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_calendar = IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_calendar_empty = IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_calendar_download = IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_navigate = IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_send = IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_aim = IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_share = IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_edit = IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_star_filled = IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_star = IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque = IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque_empty = IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mosque_favorite = IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_info1 = IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_map = IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_settings_regional = IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_theme = IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_clock = IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_language = IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_heart = IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_heart_filled = IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_update = IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_help = IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tell_a_friend = IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_copyright = IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_about = IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tutorial = IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
